<?= IncludeCSS("team.css"); ?>
<? 
$editor = false;
if ($this->UserLoggedIn()) {
    $user = $this->GetUser();
    $editor = $user->CanEdit("Team", $this->team->id);
    $publisher = $user->CanPublish("Team", $this->team->id);
    $admin = $user->CanAdmin("Team", $this->team->id);
}
?>
<? \simp\Module::Show("SectionMenu", array("current" => 'team', "entity_type" => 'Team', "entity_id" => $this->team->id)); ?>
<h1 class="title"><?= $this->team->name; ?></h1>
<? if ($editor): ?>
<ul class="admin-menu">
    <li><?= l("new article", Path::content_news_add_team($this->team->id)); ?></li>
    <li><?= l("upload image", Path::content_image_add()); ?></li>
    <li><?= l("new event", Path::content_event_add_team($this->team->id)); ?></li>
    <? if ($publisher): ?>
    <li><?= l("manage articles", Path::content_news()); ?></li>
    <li><?= l("manage images", Path::content_image()); ?></li>
    <li><?= l("manage events", Path::content_event()); ?></li>
    <? endif; ?>
    <? if ($admin): ?>
    <li><?= l("administer", Path::admin_teams_show($this->team->id)); ?></li>
    <? endif; ?>
</ul>
<? endif; ?>
<? if ($this->team->image): ?>
<div class="team-photo">
    <img src="<?= $this->team->img_path; ?>" />
</div>
<? endif; ?>
<? foreach ($this->news as $article): ?>
<div class="article">
    <p class="title"><?= l($article->title, Path::news_show($article->id)); ?></p>
    <div class="sub-title">
        <? if ($editor): ?>
        <div class="link">
            <?= l("edit this article", Path::content_news_edit_team($this->team->id, $article->id)); ?><br />
        </div>
        <? endif; ?>
        <div class="date">
            <?= TimeAgoInWords($article->updated_on); ?> ago
        </div>
    </div>
    <div class="body"><?= $article->body; ?></div>
    <?/*p><?= l("Read more...", Path::news_show($article->id)); ?></p*/?>
</div>
<? endforeach; ?>
