<fieldset>
    <legend>Field Information</legend>
    <table class="form">
        <tr>
            <td><strong>Enter a name for this field/complex</strong></td>
            <td><?= TextField($this->field, 'name', array('size' => 40)); ?></td>
        </tr>
        <tr>
            <td><strong>Enter the location for this field (e.g. street address)</strong></td>
            <td><?= TextField($this->field, 'address', array('size' => 40)); ?></td>
        </tr>
        <tr>
            <td><strong>Enter a map link (e.g. google, Bing, MapQuest, etc.)</strong></td>
            <td><?= TextField($this->field, 'map_link', array('size' => 40)); ?></td>
        </tr>
        <tr>
            <td><strong>Select the current status of the field</strong></td>
            <td><?= SimpleSelect($this->field, 'status', $this->field->status_options); ?></td>
        </tr>
        <tr>
            <td><strong>Optional Status Comment</strong></td>
            <td><?= TextArea($this->field, 'comment', 3, 40); ?></td>
        <tr>
            <td><strong>Todo: add map upload</strong></td>
            <td>&nbsp;</td>
        </tr>
    </table>
</fieldset>
