<ul class="menu">
    <? $class = $this->current == 'main' || $this->current == '' ? array('class' => 'selected') : NULL; ?>
    <li><?= l("Home", Path::home(), $class); ?></li>
    <? $class = NULL; ?>
    <? foreach ($this->GetPrograms() as $program): ?>
        <? if (SnakeCase($this->current) == SnakeCase($program->name))
                $class = array('class' => 'selected'); 
        ?>
    <li><?= l($program->name, \Path::Relative(SnakeCase($program->name)), $class); ?></li>
        <? $class = NULL; ?>
    <? endforeach; ?>
</ul>
