<p><strong>Complexes</strong></p>
<?= l("Add New Complex", path::module('field_conditions', 'admin', 'add'));?>
<? if (count($this->complexes) > 0): ?>
<table>
    <tr>
        <th>Complex</th>
        <th>Location</th>
        <th>Status</th>
        <th>Status Date</th>
        <th>Map Link</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <? foreach ($this->complexes as $complex): ?>
    <tr>
        <td><?= $complex->name; ?></td>
        <td><?= $complex->address; ?></td>
        <td><?= $complex->status_text; ?></td>
        <td><?= FormatDateTime($complex->updated_on); ?></td>
        <td><?= l("map", $complex->map_link, array("target" => 'blank')); ?></td>
        <td><?= l("Edit", Path::module('field_conditions', 'admin', 'edit', $complex->id)); ?></td>
        <td>
            <?= l("Delete", Path::module('field_conditions', 'admin', 'delete', $complex->id), array("method" => "delete"));?>
        </td>
    </tr>
    <? endforeach; ?>
</table>
<? endif; ?>

