<p><strong>Fields</strong></p>
<?= l("Add New Field", path::module('field_conditions', 'admin', 'add'));?>
<? if (count($this->fields) > 0): ?>
<table>
    <tr>
        <th>Field</th>
        <th>Location</th>
        <th>Status</th>
        <th>Status Date</th>
        <th>Map Link</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <? foreach ($this->fields as $field): ?>
    <tr>
        <td><?= $field->name; ?></td>
        <td><?= $field->address; ?></td>
        <td><?= $field->status_text; ?></td>
        <td><?= FormatDateTime($field->updated_on); ?></td>
        <td><?= l("map", $field->map_link, array("target" => 'blank')); ?></td>
        <td><?= l("Edit", Path::module('field_conditions', 'admin', 'edit', $field->id)); ?></td>
        <td>
            <?= l("Delete", Path::module('field_conditions', 'admin', 'delete', $field->id), array("method" => "delete"));?>
        </td>
    </tr>
    <? endforeach; ?>
</table>
<? endif; ?>

