<p>Field Conditions</p>
<div class="module">
<? foreach ($this->fields as $field): ?>
    <strong><?= $field->name; ?></strong><br />
    <table style="width:100%;">
        <tr>
            <td><?= $this->Time($field); ?></td>
            <td><?= $this->Status($field); ?></td>
        </tr>
        <tr>
            <td colspan='2'><?= $field->comment; ?></td>
        </tr>
    <? if (IsLoggedIn())
       {
           $user = CurrentUser();
       }
    ?>
    <? if ($this->HasAccess($user, "update_status")): ?>
        <tr>
            <td colspan='2'><?= l("Update Status", Path::module('field_conditions', 'admin', 'update_status', $field->id)); ?></td>
        </tr>
    <? endif; ?>
    </table>
<? endforeach; ?>
</div>
