<div class="module">
    <div class="title">
        <ul class="menu">
            <li>Field Conditions</li>
        </ul>
    </div>
    <div class="content">
    <? foreach ($this->fields as $field): ?>
        <div class="field">
            <strong>
                <?= l("$field->name", Path::module('field_conditions', 'show_field', $field->id)); ?>
            </strong>
            <div style="float:right;"><?= l("location", $field->map_link, array('external' => 'true')); ?></div>
            <br />
            <?= $this->Status($field); ?>
            <span class="comment"><?= $field->comment; ?></span>
            <div class="date">
                <?= $this->Time($field); ?>
            </div>
            <? if (IsLoggedIn() && $this->HasAccess(CurrentUser(), "update_status")): ?>
            <?= l("Update Status", Path::module('field_conditions', 'admin', 'update_status', $field->id)); ?>
            <? endif; ?>
        </div>
<? endforeach; ?>
    </div>
</div>
