<h1>Update Status for "<?= $this->complex->name; ?>"</h1>
<?= GetErrorsFor($this->complex); ?>
<?= FormTag("complex", \simp\Request::PUT); ?>
    <p><strong>Status</strong><p>
    <?= SimpleSelect($this->complex, 'status', $this->complex->status_options); ?>
    <p><strong>Comment</strong></p>
    <?= TextArea($this->complex, 'comment', 3, 40); ?><br />
    <input type="submit" value="Update" />
<?= EndForm(); ?>
