<strong>Add article to section: </strong>
<?= SimpleSelect($this->article, 'entity_id', $this->programs); ?><br />
<strong>Enter a short title: </strong><?= TextField($this->article, 'short_title'); ?><br />
<strong>Enter title: </strong><?= TextField($this->article, 'title');?> <br/>
<strong>Intro: </strong><?= TextArea($this->article, 'intro'); ?><br />
<strong>Body: </strong><?= TextArea($this->article, 'body'); ?><br />

