<h1>Content Manager</h1>
<?= l("Create an article", Path::content_news_add()); ?>
<h2>Published Articles</h2>
<? if (count($this->published_articles) < 1): ?>
    <p>None</p>
<? else: ?>
<table class="pretty">
    <tr>
        <th>Section</th><th>Article Title</th><th>Expiration</th><th colspan="2">&nbsp;</th>
    </tr>
    <? foreach ($this->published_articles as $article): ?>
    <tr>
        <td>
            <?= $article->entity_type; ?>:
            <strong>
            <?=$article->entity_name; ?>
            </strong>
        </td>
        <td><?= $article->title; ?></td>
        <td><?= FormatDateTime($article->expiration); ?>
        <td><?= l("Edit", Path::content_news_edit($article->id)); ?></td>
        <td><?= l("Remove", Path::content_news_delete($article->id), array("method" => "delete")); ?></td>
    </tr>
    <? endforeach; ?>
</table>
<? endif; ?>
<h2>Unpublished Articles</h2>
<? if (count($this->unpublished_articles) < 1): ?>
    <p>None</p>
<? else: ?>
<table class="pretty">
    <tr>
        <th>Section</th><th>Article Title</th><th>Publish On</th><th>Expires</th><th colspan="2">&nbsp;</th>
    </tr>
    <? foreach ($this->unpublished_articles as $article): ?>
    <tr>
        <td><?= $article->entity_type; ?>:<strong><?= $article->entity_name; ?></td>
        <td><?= $article->title; ?></td>
        <td><?= FormatDateTime($article->publish_on); ?>
        <td><?= FormatDateTime($article->expiration); ?>
        <? if ($this->GetUser()->CanPublish($article->entity_type, $article->entity_id)): ?>
        <td><?= l("Publish Now", Path::content_news_publish($article->id)); ?></td>
        <? endif; ?>
        <td><?= l("Edit", Path::content_news_edit($article->id)); ?></td>
        <td><?= l("Remove", Path::content_news_delete($article->id), array("method" => "delete")); ?></td>
    </tr>
    <? endforeach; ?>
</table>
<? endif; ?>
