<h1 class="title"><?= SiteName(); ?> Administration</h1>
<? $group = ""; ?>
<div class="coach">
<table>
<? foreach($this->staff as $staff_member): ?>
    <? if ($group != $staff_member->group): ?>
        <? $group = $staff_member->group; ?>
    <tr><th colspan="4"><h3 class="subtitle"><?= $group; ?><hr /></h3></th></tr>
    <? endif; ?>
    <tr>
        <th>
            <? if ($staff_member->image): ?>
            <img src="<?= $staff_member->img_path; ?>"/>
            <? endif; ?>
        </th>

        <td><?= $staff_member->title; ?></td>
        <td><?= l("{$staff_member->first_name} {$staff_member->last_name}", Path::staff("staff_member", $staff_member->id)); ?></td>
        <td><?= ObsEmailLink($staff_member->email); ?></td>
    </tr>
<? endforeach;?>
</table>
</div>
