<h1 class="title"><?= SiteName(); ?> Staff Coaches</h1>
<div class="coach">
<table>
<? foreach($this->coaches as $coach): ?>
    <tr>
        <th><img src="<?= $coach->img_path; ?>"/></th>
        <td><?= l("{$coach->first_name} {$coach->last_name}", Path::staff_coach($coach->id)); ?></td>
        <td><?= Coach::$coach_titles[$coach->title]; ?></td>
        <td><?= ObsEmailLink($coach->email); ?></td>
    </tr>
<? endforeach; ?>
</table>
</div>
