<h1 class="title">Schedules</h1>
<h2>Current Schedules</h2>
<p><?= l("Download CSV", Path::admin_schedule_download()); ?></p>
<? if (count($this->schedules) > 0): ?>
<table class="pretty">
    <tr><th>Schedule</th><th>Level</th><th>Start</th><th>End</th><th>Reschedules Allowed</th><th>Divisions</th><th>Actions</th></tr>
    <? foreach ($this->schedules as $schedule): ?>
    <tr>
        <td><?= l($schedule->name, Path::admin_schedule_show($schedule->id)); ?></td>
        <td><?= Division::$levelopts[$schedule->level]; ?></td>
        <td><?= $schedule->start_date_str; ?></td>
        <td><?= $schedule->end_date_str; ?></td>
        <td><?= $schedule->allow_reschedules == true ? "Yes" : "No"; ?></td>
        <td>
        <? foreach ($schedule->divisions as $div): ?>
            <?= $div->name; ?><br />
        <? endforeach; ?>
        </td>
            <td><?= l("edit", Path::admin_schedule_edit($schedule->id)); ?> <?= l("delete", Path::admin_schedule_delete($schedule->id), array("method" => "delete"));?></td>
    </tr>
    <? endforeach; ?>
</table>
<?= l("Create new schedule", Path::admin_schedule_add()); ?>
<? else: ?>
    None.  <?= l("Add one.", Path::admin_schedule_add()); ?>
<? endif; ?>
<br />
<h2>Past Schedules</h2>
<? if (count($this->past_schedules) > 0): ?>
<table class="pretty">
    <tr><th>Schedule</th><th>Level</th><th>Start</th><th>End</th><th>Actions</th></tr>
    <? foreach ($this->past_schedules as $schedule): ?>
    <tr>
        <td><?= l($schedule->name, Path::admin_schedule_show($schedule->id)); ?></td>
        <td><?= Division::$levelopts[$schedule->level]; ?></td>
        <td><?= $schedule->start_date_str; ?></td>
        <td><?= $schedule->end_date_str; ?></td>
        <td><?= l("edit", Path::admin_schedule_edit($schedule->id)); ?></td>
    </tr>
    <? endforeach; ?>
</table>
<? else: ?>
    None.  
<? endif; ?>
