<h1 class="title"><?= $this->schedule->name; ?></h1>
<?= l("upload schedule data (GotSoccer CSV)", Path::admin_schedule_upload($this->schedule->id)); ?>
<? foreach ($this->schedule->divisions as $division): ?>
<h2><?= $division->name; ?></h2>
<table class="pretty">
    <tr><th>Date</th><th>Time</th><th>Field</th><th>Home</th><th>Away</th></tr>
        <? foreach ($division->games as $game): ?>
    <tr>
        <td><?= $game->date_str; ?></td>
        <td><?= $game->start_time; ?> - <?= $game->end_time; ?></td>
        <td><?= $game->field->name; ?></td>
        <td><?= $game->home != false ? $game->home : $game->home_club; ?></td>
        <td><?= $game->away != false ? $game->away : $game->away_club; ?></td>
    </td>
        <? endforeach; ?>
</table>
<? endforeach; ?>
