<h1><?= $this->program->name; ?></h1>
<p><?= $this->program->description; ?></p>
<? foreach ($this->news as $article): ?>
<div class="article">
    <h2><?= l($article->title, GetArticlePath('show', $article)); ?></h2>
        <span class="date">
            <?= FormatDateTime($article->updated_on, "D M d, Y"); ?>
        </span>
    <p><?= $article->intro; ?></p>
    <p><?= l("Read more...", GetArticlePath('show', $article)); ?></p>
</div>
<? endforeach; ?>
