<? 
$editor = false;
if ($this->UserLoggedIn()) {
    $user = $this->GetUser();
    $editor = $user->CanEdit("Program", $this->program->id);
    $publisher = $user->CanPublish("Program", $this->program->id);
    $admin = $user->CanAdmin("Program", $this->program->id);
}
?>
<h1 class="title"><?= $this->program->name; ?></h1>
<h3 class="sub-title"><?= $this->program->description; ?></h3>
<ul class="section-menu">
    <li><?= l("Events", Path::event_calendar("program", $this->program->id)); ?></li>
    <? if ($this->program->has_teams): ?>
    <li><?= l("Teams", Path::Relative("{$this->program->name}/teams")); ?></li>
    <? endif; ?>
</ul>
<? if ($editor): ?>
<ul class="menu">
    <li><?= l("create new article", Path::content_news_add_program($this->program->id)); ?></li>
    <? if ($publisher): ?>
    <li><?= l("manage articles", Path::content_news()); ?></li>
    <? endif; ?>
    <? if ($admin): ?>
    <li><?= l("administer {$this->program->name} program", Path::admin_program_show($this->program->id)); ?></li>
    <? endif; ?>
</ul>
<? endif; ?>
<? foreach ($this->news as $article): ?>
<div class="article">
    <h2><?= l($article->title, GetArticlePath('show', $article)); ?></h2>
    <? if ($editor): ?>
    <?= l("edit this article", Path::content_news_edit_program($this->program->id, $article->id)); ?><br />
    <? endif; ?>
        <span class="date">
            <?= FormatDateTime($article->updated_on, "D M d, Y"); ?>
        </span>
    <p><?= $article->intro; ?></p>
    <p><?= l("Read more...", GetArticlePath('show', $article)); ?></p>
</div>
<? endforeach; ?>
