<h1>Edit User</h1>
<? $errors = $this->user->GetErrors();
   if (count($errors) > 0):
?>
<div class='errors'>
    <ul>
    <? foreach ($errors as $error): ?>
        <li><?= $error; ?></li>
    <? endforeach; ?>
    </ul>
</div>
<? endif; ?>
<?= FormTag("user", \simp\Request::PUT, path::admin_user($this->user->id)) ?>
    <? require("_form.phtml"); ?>
    <input type="submit" value="Update"/>
<?= EndForm(); ?>
