<?php
$editor = false;
if ($this->UserLoggedIn()) {
    $user = $this->GetUser();
    $editor = $user->CanEdit($this->page->entity_type, $this->page->entity_name);
    $entity_type = SnakeCase($this->page->entity_type);
    //$publisher = $user->CanPublish("Program", $this->program->id);
    //$admin = $user->CanAdmin("Program", $this->program->id);
}
?>
<? \simp\Module::Show("SectionMenu", array("current" => $this->page->short_title, "entity_type" => $this->page->entity_type, "entity_id" => $this->page->entity_id)); ?>
<h1 class="title"><?= $this->page->entity_name; ?></h1>
<div class="article">
    <p class="title"><?= $this->page->title; ?></p>
    <div class="sub-title">
    <? if ($editor): ?>
        <div class="link">
        <?= l("edit this page", Path::content_page_edit(
            $entity_type, $this->page->entity_id, $this->page->id)); ?><br />
        </div>
    <? endif; ?>
        <div class="date">
            <?= TimeAgoInWords($this->page->updated_on); ?> ago
        </div>
    </div>
    <div class="body"><?= $this->page->copy; ?></div>
</div>
