<h2><?= SiteName();?> News</h2>
<? foreach ($this->news as $article): ?>
<div class="article">
    <h2><?= l($article->title, Path::news($article->id)); ?></h2>
        <span class="date">
            <?= FormatDateTime($article->updated_on, "D M d, Y"); ?>
        </span>
    <? if ($article->image): ?>
    <div class="image"><img src="<? $article->img_path; ?>" /></div>
    <? endif; ?>
    <p><?= $article->intro; ?></p>
    <p><?= l("Read more...", Path::news($article->id)); ?>
</div>
<? endforeach; ?>
