<?
$editor = false;
if ($this->UserLoggedIn()) {
    $user = $this->GetUser();
    $editor = $user->CanEdit($this->article->entity_type, $this->article->entity_name);
    $entity_type = SnakeCase($this->article->entity_type);
    //$publisher = $user->CanPublish("Program", $this->program->id);
    //$admin = $user->CanAdmin("Program", $this->program->id);
}
?>
<? \simp\Module::Show("SectionMenu", array("current" => 'index', "entity_type" => $this->article->entity_type, "entity_id" => $this->article->entity_id)); ?>
<div class="article">
    <p class="title"><?= $this->article->title; ?></p>
    <div class="sub-title">
    <? if ($editor): ?>
        <div class="link">
        <?= l("edit this article", Path::content_news_edit(
            $entity_type, $this->article->entity_id, $this->article->id)); ?><br />
        </div>
    <? endif; ?>
        <div class="date">
            <?= TimeAgoInWords($this->article->updated_on); ?> ago
        </div>
    </div>
    <div class="body"><?= $this->article->body; ?></div>
</div>
