<h1 class="title">New Reschedule Request</h1>
<?= GetErrorsFor($this->reschedule); ?>
<?= FormTag("request", \simp\Request::POST, Path::reschedule_selectfield($this->reschedule->id)); ?>

<fieldset><legend>Select the game you are rescheduling</legend>
    <h3>
        games for 
        <?= "{$this->reschedule->division} {$this->reschedule->age} {$this->reschedule->gender}"; ?> 
        on <?=$this->reschedule->orig_date_str; ?>
    </h3>
<table class="pretty">
    <tr><th>&nbsp;</th><th>game Time</th><th>Home</th><th>Away</th></tr>
<? foreach ($this->games as $game): ?>
    <tr>
        <td><?= RadioButton($this->reschedule, "game_id", $game->id); ?></td>
        <td><?= $game->start_time; ?> - <?= $game->end_time; ?></td>
        <td><?= $game->home != false ? $game->home : $game->home_club; ?></td>
        <td><?= $game->away != false ? $game->away : $game->away_club; ?></td>
    </tr>
<? endforeach; ?>
</table>
</fieldset>
<fieldset><legend>Enter Candidate Dates</legend>
<table class="form">
    <tr>
        <th class="label">First Choice</th>
<? $args = "maxDate: '+4m', minDate: '+0d', changeYear: false, changeMonth: true, showOn: 'both', showAnim: 'drop', showButtonPanel: 'true', yearRange: 'c-18:c+18'"; ?>
        <td class="entry"><?= DatePicker($this->reschedule, "first_choice_str", array('args' => $args)); ?></td>
    </tr>
    <tr>
        <th class="label">Second Choice</th>
        <td class="entry"><?= DatePicker($this->reschedule, "second_choice_str", array('args' => $args)); ?></td>
    </tr>
</fieldset>
</table>
<input type="submit" value="Continue to Next Step..." />
<?= EndForm(); ?>
