<h1 class="title">New Reschedule Request</h1>
<?= GetErrorsFor($this->reschedule); ?>
<?= FormTag("request", \simp\Request::POST, Path::reschedule_submit()); ?>
    <input type="hidden" name="Reschedule['affirmed']" value="<?= $this->affirmed; ?>" />
    <fieldset><legend>Match Information</legend>
        <table class="form">
            <tr>
                <th class="label">Original Match Date</th>
                <td class="entry"><?= DatePicker($this->reschedule, 'orig_date_str'); ?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Match ID</th>
                <td class="entry"><?= TextField($this->reschedule, 'match_id', array('size' => 4)); ?></td>
                <td class="help">This is the match ID from the schedule</td>
            </tr>
            <tr>
                <th class="label">First Date Choice</th>
                <td class="entry"><?= DatePicker($this->reschedule, 'first_date_str');?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">First Date Time of Day</th>
                <td class="entry"><?= SimpleSelect($this->reschedule, 'first_tod', Reschedule::$tod_opts);?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Second Date Choice</th>
                <td class="entry"><?= DatePicker($this->reschedule, 'second_date_str');?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Second Date Time of Day</th>
                <td class="entry"><?= SimpleSelect($this->reschedule, 'second_tod', Reschedule::$tod_opts);?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Comments to Rescheduler</th>
                <td class="entry" colspan="2"><?= TextArea($this->reschedule, 'comments', 3, 40); ?> </td>
            </tr>
        </table> 
    </fieldset>
    <fieldset><legend>Contact Information</legend>
        <table class="form">
            <tr>
                <th class="label">Requestor TODO make this read only</th>
                <td class="entry"><?= TextField($this->reschedule, 'requestor_name'); ?></td>
            </tr>
            <tr>
                <th class="label"></th>
                <td class="entry"></td>
            </tr>
            <tr>
                <th class="label"></th>
                <td class="entry"></td>
            </tr>
            <tr>
                <th class="label"></th>
                <td class="entry"></td>
            </tr>
        </table>
    </fieldset>
    <input type="submit" value="Submit Request" />
<?= EndForm(); ?>
