<h1 class="title">New Reschedule Request</h1>
<h2 class="subtitle"><?= $this->reschedule->schedule->name; ?></h2>
<?= GetErrorsFor($this->reschedule); ?>
<?= FormTag("request", \simp\Request::POST, Path::reschedule_match()); ?>
    <input type="hidden" name="Reschedule[affirmed]" value="<?= $this->affirmed; ?>" />
    <input type="hidden" name="Reschedule[schedule_id]" value="<?= $this->reschedule->schedule_id; ?>" />
    <fieldset><legend>Match Information</legend>
        <table class="form">
            <tr>
                <th class="label">Division</th>
                <td class="entry">
                    <?= SimpleSelect($this->reschedule, 'division_id', $this->reschedule->DivisionOpts()); ?></td>
                <td class="help">Division game is scheduled in</td>
            </tr>
            <tr>
                <th class="label">Original Match Date</th>
<? $args = "maxDate: '+4m', minDate: '+0d', changeYear: false, changeMonth: true, showOn: 'both', showAnim: 'drop', showButtonPanel: 'true', yearRange: 'c-18:c+18'"; ?>
                <td class="entry"><?= DatePicker($this->reschedule, 'orig_date_str', array('args' => $args)); ?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Reason for Reschedule</th>
                <td class="entry"><?= SimpleSelect($this->reschedule, 'reschedule_reason', Reschedule::$reschedule_reasons); ?></td>
                <td class="help">
                    Select the reason for a reschedule.  Note that "Coach Conflict" refers 
                    to a coach not able to attend a match due to another club soccer game.
                    Reschedules should not be taken lightly as finding open fields and referees can
                    be a complicated, time-consuming process. As such, a request may not be approved
                    for certain reasons, including but not limited to, "OU/TX football game," 
                    "Birthday Party," "Weather is forecast to be too cold," etc.
                </td>
                    
<? /*
            <tr>
                <th class="label">Match ID</th>
                <td class="entry"><?= TextField($this->reschedule, 'match_id', array('size' => 4)); ?></td>
                <td class="help">This is the match ID from the schedule</td>
            </tr>
            <tr>
                <th class="label">First Date Choice</th>
                <td class="entry"><?= DatePicker($this->reschedule, 'first_date_str');?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">First Date Time of Day</th>
                <td class="entry"><?= SimpleSelect($this->reschedule, 'first_tod', Reschedule::$tod_opts);?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Second Date Choice</th>
                <td class="entry"><?= DatePicker($this->reschedule, 'second_date_str');?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Second Date Time of Day</th>
                <td class="entry"><?= SimpleSelect($this->reschedule, 'second_tod', Reschedule::$tod_opts);?></td>
                <td class="help">&nbsp;</td>
            </tr>
            <tr>
                <th class="label">Comments to Rescheduler</th>
                <td class="entry" colspan="2"><?= TextArea($this->reschedule, 'comments', 3, 40); ?> </td>
            </tr>
 */?>
        </table> 
    </fieldset>
    <fieldset><legend>Contact Information</legend>
        <table class="form">
            <tr>
                <th class="label">Requestor</th>
                <td class="entry"><?= TextField($this->reschedule, 'requestor_name', array('readonly' => true)); ?></td>
            </tr>
            <tr>
                <th class="label">Requestor Email</th>
                <td class="entry"><?= TextField($this->reschedule, 'requestor_email', array('readonly' => true)); ?></td>
            </tr>
            <tr>
                <th class="label">Opposing Coach/Manager</th>
                <td class="entry"><?= TextField($this->reschedule, 'opponent_name'); ?></td>
            </tr>
            <tr>
                <th class="label">Opposing Coach/Manager Email</th>
                <td class="entry"><?= TextField($this->reschedule, 'opponent_email'); ?></td>
            </tr>
        </table>
    </fieldset>
    <input type="submit" value="Continue to Next Step..." />
<?= EndForm(); ?>
