<h1 class="title">Reschedule Request Validation</h1>
<? if ($this->show_form == true): ?>
<p>
<?= $this->message; ?>
</p>
<p>
<?= FormTag("resched", \simp\Request::POST); ?>
Please enter the token you received via email:<br/>
<input type="text" name="token" size="40"/>
<input type="submit" value="Submit" />
<?= EndForm(); ?>
</p>
<? else: ?>
<h3>Original Match Information</h3>
<table class="form">
    <tr><th class="label">Schedule</th><td class="entry"><?= $this->reschedule->schedule->name; ?></td></tr>
    <tr><th class="label">Division</th><td class="entry"><?= $this->reschedule->game->division; ?></td></tr>
    <tr><th class="label">Match ID</th><td class="entry"><?= $this->reschedule->game->gotsoccer_id; ?></td></tr>
    <tr><th class="label">Original Date</th><td class="entry"><?= $this->reschedule->orig_date_str; ?></td></tr>
    <tr><th class="label">Original Time</th><td class="entry"><?= $this->reschedule->game->start_time; ?></td></tr>
    <tr><th class="label">Home Team</th><td class="entry"><?= $this->reschedule->game->home_club; ?> <?= $this->reschedule->game->home; ?></td></tr>
    <tr><th class="label">Away Team</th><td class="entry"><?= $this->reschedule->game->away_club; ?> <?= $this->reschedule->game->away; ?></td></tr>
</table>
<br />
<h3>Reschedule Information</h3>
<table class="form">
    <tr><th class="label">First Date Choice</th><td class="entry"><?= $this->reschedule->first_choice_str; ?> <?= Reschedule::$tod_opts[$this->reschedule->first_tod]; ?></td></tr>
    <tr><th class="label">Second Date Choice</th><td class="entry"><?= $this->reschedule->second_choice_str;?> <?= Reschedule::$tod_opts[$this->reschedule->second_tod]; ?></td></tr>
    <tr><th class="label">Requestor</th><td class="entry"><?= $this->reschedule->requestor_name; ?> <?= ObsEmailLink($this->reschedule->requestor_email); ?></td></tr>
    <tr><th class="label">Opponent Representative</th><td class="entry"><?= $this->reschedule->opponent_name; ?> <?= ObsEmailLink($this->reschedule->opponent_email); ?></td></tr>
    <tr><th class="label">Comments to Scheduler</th><td class="entry"><?= $this->reschedule->comments; ?></td></tr>
</table>
<p>
    You will be contacted via email when this reschedule is accepted or denied.
</p>
<? endif; ?>
