<? if(count($this->events) > 0): ?> 
<div class="module">
    <div class="title">
        <ul class="menu">
            <li>Upcoming <?=$this->entity_name;?> Events</li>
            <li><?=l("Calendar", Path::event_calendar($path_args)); ?></li>
        </ul>
<? /*
    <table style="padding:0;width:100%;">
        <tr>
        <td>Upcoming <?=$this->entity_name;?> Events</td>
            <? $path_args = isset($this->entity_id) ? "{$this->entity_type}/{$this->entity_id}" : $this->entity_type; ?>
            <td style="text-align:right;"><?= l("Calendar", Path::event_calendar($path_args)); ?></td>
        </tr>
    </table>
 */?>
    </div>
    <div class="content">
<? foreach ($this->events as $date => $events): ?>
    <?/*<strong><?= FormatDateTime($date, "m/d/Y"); ?></strong><br />*/?>
    <? foreach ($events as $event): ?>
        <div class="event">
            <span class="date"><?= FormatDateTime($date, "m/d/Y"); ?>
            <? if ($event->all_day): ?>
            All Day
            <? else: ?>
            <?= FormatDateTime($event->start_time, "H:i"); ?>
            <? endif; ?>
            </span>
            <? if ($this->show_category): ?>
                <span class="event-category"><?=$event->category?></span>
            <? endif; ?>
            <br /><?= l($event->title, Path::event_show($event->id)); ?>
        </div>
    <? endforeach; ?>
<? endforeach; ?>
    </div>
</div>
<? endif; ?>
