<p>Upcoming Events</p>
<div class="module">
<? foreach ($this->events as $date => $events): ?>
    <strong><?= FormatDateTime($date, "m/d/Y"); ?></strong><br />
    <? foreach ($events as $event): ?>
        <? if ($event->all_day): ?>
        All Day
        <? else: ?>
        <?= FormatDateTime($event->start_time, "H:i"); ?>
        <? endif; ?>
        - <?= $event->title; ?>
        <br/>
    <? endforeach; ?>
    <br />
<? endforeach; ?>
</div>
