<? if(count($this->events) > 0): ?> 
<div class="module">
    <div class="title">
        <ul class="menu">
            <li>Upcoming '<?=$this->entity_name;?>' Events</li>
            <? $path_args = isset($this->entity_id) ? "{$this->entity_type}/{$this->entity_id}" : $this->entity_type; ?>
            <li><?=l("Calendar", Path::event_calendar($path_args)); ?></li>
        </ul>
<? /*
    <table style="padding:0;width:100%;">
        <tr>
        <td>Upcoming <?=$this->entity_name;?> Events</td>
            <? $path_args = isset($this->entity_id) ? "{$this->entity_type}/{$this->entity_id}" : $this->entity_type; ?>
            <td style="text-align:right;"><?= l("Calendar", Path::event_calendar($path_args)); ?></td>
        </tr>
    </table>
 */?>
    </div>
    <div class="content">
<? $age = 0; ?>
<? foreach ($this->events as $date => $events): ?>
    <?/*<strong><?= FormatDateTime($date, "m/d/Y"); ?></strong><br />*/?>
        <div class="event-date">
        <? $now = time(); ?>
        <? if (date("m/d/Y", $date) == (date("m/d/Y", $now))): ?>
            Today
        <? else: ?>
            <?= FormatDateTime($date, "m/d/Y"); ?>
        <? endif; ?>
        </div>
        <div class="event age-<?= $age ?>">
        <table style="width:100%">
        <? foreach ($events as $event): ?>
            <tr>
                <td style="width:30%;vertical-align:top;">
                <? if ($event->all_day): ?>
                All Day
                <? else: ?>
                <?= FormatDateTime($event->start_time, "g:i a"); ?>
                <? endif; ?>
                <? if ($this->show_category): ?>
                    <br />
                    <span class="event-category"><?=$event->category?></span>
                <? endif; ?>
                </td>
                <td style="text-align:right;">
                <?= l($event->title, Path::event_show($event->id)); ?>
                </td>
            </tr>
        <? endforeach; ?>
        </table>
        </div>
    <? $age++; ?>
<? endforeach; ?>
    </div>
</div>
<? endif; ?>
