<h1 class="title">Administrator Console</h1>
<div class="cfg-group">
    <h1>General Configuration</h1>
    <table>
        <tr>
            <th style="width:25%"><?= l("Site Configuration", Path::admin_configuration()); ?></th>
            <th style="width:25%"><?= l("Cache Management", Path::admin_cache()); ?></th>
            <th style="width:25%"><?= l("User Editor", Path::admin_user()); ?></th>
            <th style="width:25%"><?= l("Manage Plug-ins", Path::admin("plug_in")); ?></th>
        </tr>
        <tr>
            <td>Set site-specific configuration parameters such as Site Name, Session Timeout, Site Email, etc.</td>
            <td>[ADVANCED] Inspect cached items, clear the site cache, etc (do this if things seem out of whack).</td>
            <td>Add/Modify user accounts</td>
            <td>Install/Enable/Disable plug-ins (special menus, modules, etc.)</td>
        </tr>
    </table>
</div>
<div class="cfg-group">
    <h1>Club Information</h1>
    <table>
        <tr>
            <th style="width:20%"><?= l("Club Information", Path::admin("club_information")); ?></th>
            <th style="width:20%"><?= l("Club Program Editor", Path::admin_program()); ?></th>
            <th style="width:20%"><?= l("Coaches", Path::admin_coaches()); ?></th>
            <th style="width:20%"><?= l("Club Staff", Path::admin_staff()); ?></th>
            <th style="width:20%"><?= l("Teams", Path::admin_teams()); ?></th>
        </tr>
        <tr>
            <td>Modify information about club (shown on "About" page)</td>
            <td>Add/Edit/Delete Club programs (leagues, tournaments, camps, etc.)</td>
            <td>Add/Edit/Delete Club Coach information</td>
            <td>Add/Edit/Delete Club Staff (board members, commissioners, etc.)</td>
            <td>Add/Edit/Delete Club Teams</td>
        </tr>
    </table>
<div class="cfg-group">
    <h1>Schedule</h1>
    <table>
        <tr>
            <th style="width:20%"><?= l("Fields", Path::admin_fields()); ?></th>
            <th style="width:20%"><?= l("Schedule", Path::admin_schedule()); ?></th>
            <th style="width:20%"><?= l("Reschedule", Path::admin_reschedule()); ?></th>
        </tr>
        <tr>
            <td>Add/Edit/Delete Field information for schedules.</td>
            <td>Add/Edit/Delete/Upload Schedule information</td>
            <td>Manage Reschedule Requests</td>
        </tr>
    </table>
</div>


