<?
global $REL_PATH;
$request = $data['reschedule'];
$site_name = $data['site_name'];
$host = $data['host'];
?>
<p>A reschedule request has been submitted for a match by <strong><?= $request->requestor_name; ?></strong>
and you have been designated as the opponent representative.
</p>
<p>To ensure all parties are in agreement, as the opponent representative you must validate the request by following this
<a href="http://<?= $host . $REL_PATH; ?>reschedule/validate/<?= $request->id ?>/<?= $request->verification_string; ?>">validation link</a>.
</p>
<p>( You're validation token is: <em><?= $request->verification_string; ?></em> )</p>
<strong>Match Information</strong>
<table>
<tr><td><?= $request->schedule->name; ?></td> <td><?= $request->division->name; ?></td></tr>
<tr><td>Match ID:</td><td><?= $request->game->gotsoccer_id; ?></td></tr>
<tr><td>Original Date:</td><td><?= $request->orig_date_str; ?></td></tr>
<tr><td>Original Time:</td><td><?= $request->game->start_time; ?></td></tr>
<tr><td>Original Field:</td><td><?= $request->game->field->name; ?></td></tr>
<tr><td>Home Team:</td><td><?= $request->game->home_club; ?> <?= $request->game->home; ?></td></tr>
<tr><td>Away Team:</td><td><?= $request->game->away_club; ?> <?= $request->game->away; ?></td></tr>
</table>
<p>The requested dates to reschedule are:</p>
<p>Reason: <?= Reschedule::$reschedule_reasons[$request->reschedule_reason]; ?></p>
<p>Comments to scheduler:</p>
<pre>
---------------------
<?= $request->comments; ?>
</pre>
<table>
    <tr><td>First Choice:</td><td><?= $request->first_choice_str; ?> <?= Reschedule::$tod_opts[$reschedule->first_tod]; ?></td></tr>
    <tr><td>Second Choice:</td><td><?= $request->second_choice_str; ?> <?= Reschedule::$tod_opts[$reschedule->second_tod]; ?></td></tr>
</table>
<p>
Thanks!<br />
<?= $site_name; ?> Robot Webmaster
</p>
