<fieldset>
<legend>Email for "<?= $this->category->name; ?>"</legend>
<input type='hidden' name='Email[category_id]' value='<?= $this->category->id; ?>' />
    <table class="form">
<? if ($this->category->classification == Category::AGE): ?>
        <tr>
            <th class="label">Associated Age Group:</th>
            <td class="entry">
                <?= SimpleSelect($this->email, 'param1', Email::$genders); ?>
                <?= SimpleSelect($this->email, 'param2', Email::$ages); ?>
                <?= SimpleSelect($this->email, 'param3', Email::$end_ages); ?>
            </td>
        </tr>
<? elseif ($this->category->classification == Category::CUSTOM): ?>
        <tr>
            <th class="label">Associated Custom Option:</th>
            <td class="entry"><?= TextField($this->email, 'param1'); ?>
            <td class="help">When user selects this option, request will go to this email</td>
        </tr>
<? endif; ?>
        <tr>
            <th class="label">Email Address:</th>
            <td class="entry"><?= TextField($this->email, 'address'); ?>
        </tr>
    </table>
</fieldset>
<fieldset>
    <legend>Additional Data To Collect</legend>
    <? if (count($this->email->data) > 0): ?>
    <p><strong>Current Data</strong></p>
    <table class="pretty">
        <tr><th style="width:15%">Label</th><th style="width:15%">Type</th><th style="width:15%">Required</th><th style="width:55%">Options</th></tr>
        <? foreach ($this->email->data as $id => $datum): ?>
        <tr>
            <td>
                <?= l("[x]", Path::module('information', 'admin', 'remove_datum', $datum->id)); ?>
                <?= $datum->label; ?>
            </td>
            <td><?= Datum::$types[$datum->type]; ?></td>
            <td><?= $datum->required ? 'yes':'no'; ?></td>
            <td><? foreach ($datum->options as $opt) echo "$opt<br />"?></td>
        </tr>
        <? endforeach; ?>
    </table>
    <? endif; ?>
    <p><strong>New Data</strong></p>
    <table class="pretty">
        <tr><th style="width:15%">Label</th><th style="width:15%">Type</th><th style="width:15%">Required</th><th style="width:55%">Options</th></tr>
    <? for($i=0;$i<10;$i++): ?>
        <tr>
            <td><?= TextField($this->email, 'datum_label', array('array' => $i)); ?></td>
            <td><?= SimpleSelect($this->email, 'datum_type', Datum::$types, array('array' => $i)); ?></td>
            <td><?= CheckBoxField($this->email, 'datum_required', array('array' => $i)); ?></td>
            <td><?= TextField($this->email, 'datum_options', array('array' => $i, 'size' => 80)); ?></td>
        </tr>
    <? endfor; ?>
    </table>
</fieldset>
