<h1 class="title"><?= $this->category->text; ?></h1>
<br />
<?= GetErrorsFor($this->info_request); ?>
<?= FormTag("contact", \simp\Request::POST); ?>
<table class="form">
    <tr>
        <th class="label">Your Name:</th> 
        <td class="entry"><?= TextField($this->info_request, 'name', array('size' => 40)); ?></td>
    </tr>
    <tr>
        <th class="label">Your Email Address:</th> 
        <td class="entry"><?= TextField($this->info_request, 'email', array('size' => 40)); ?></td>
    </tr>
<? if ($this->category->classification == Category::AGE): ?>
<?= IncludeCSS("custom-theme/jquery-ui.css"); ?>
<?= IncludeJS("jquery-ui.js"); ?>
<script type="text/javascript">
$(function($) {
    $(document).ready(function() {
        $(".date-picker").datepicker({
                maxDate: '-4y', 
                minDate: '-18y', 
                changeYear: true,
                changeMonth: true,
                showOn: 'both',
                showAnim: 'drop',
                showButtonPanel: true,
                yearRange: 'c-18:c+18'
        });
    });
});
</script>
    <tr>
        <th class="label">Player's Date of Birth:</th> 
        <td class="entry"><?= DatePicker($this->info_request, 'birthdate'); ?></td>
    </tr>
    <tr>
        <th class="label">Player's Gender:</th>
        <td class="entry"><?= SimpleSelect($this->info_request, 'gender', array(1 => 'Male', 2 => 'Female')); ?></td>
    </tr>
<? elseif ($this->category->classification == Category::CUSTOM): ?>
    <tr>
        <th class="label">Subject:</th>
        <td class="entry"><?= $this->info_request->subject; ?></td> 
    </tr>
<? endif; ?>
<? foreach($this->info_request->field_info as $id => $field): ?>
    <tr>
        <th class="label"><?= $field['label']?>:</th> 
<? 
        $tag = "";
        switch ($field['type'])
        {
        case 0:
            $tag = CheckBoxField($this->info_request, 'fields', array('array' => $id));
            break;
        case 1:
            $tag = TextField($this->info_request, 'fields', array('array' => $id, 'size' => 40));
            break;
        case 2:
            $tag = SimpleSelect($this->info_request, 'fields', $field['opt'], array('array' => $id));
            break;
        }
?>
        <td class="entry"><?= $tag; ?></td>
    </tr>
<? endforeach; ?>
    <tr>
        <th class="label">Enter your enquiry:</th> 
        <td class="entry"><?= TextArea($this->info_request, 'body'); ?></td>
    </tr>
</table>
<input type="submit" value="Submit Request" />
<? EndForm(); ?>
