<fieldset>
    <legend>Program Information</legend>
    <table class="form">
        <tr>
            <th class="label">Program Type:</th>
            <td class="entry"><?=SimpleSelect($this->program, 'type', Program::Types());?></td>
        </tr>
        <tr>
            <th class="label">Program Name:</th>
            <td class="entry"><?=TextField($this->program, 'name');?></td>
        </tr>
        <tr>
            <th class="label">Description:</th>
            <td class="entry"><?=Wysiwyg($this->program, 'description');?></td>
        </tr>
        <tr>
            <th class="label">Weight:</th>
            <td class="entry"><?=TextField($this->program, 'weight', array('size' => '2'));?></td>
        </tr>
        <tr>
            <th class="label">Default Image</th>
            <td class="entry"><?=FileSelect($this->program, 'image'); ?></td>
        </tr>
    </table>
</fieldset>    
