<p><strong>Programs</strong></p>
<?= l("Add New Program", path::admin_program_add());?>
<table class="pretty">
    <tr>
        <th>Program</th>
        <th>Weight</th>
        <th>Type</th>
        <th>Can Have Team Pages</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
<? foreach ($this->programs as $program): ?>
    <? $users = User::GetPrivilegedUsers('program', $program->id); ?>
    <tr>
        <td><?= l($program->name, Path::admin_program_show($program->id)); ?></td>
        <td><?= $program->weight; ?></td>
        <td><?= $program->Type(); ?></td>
        <td><?= $program->has_teams ? 'yes': 'no'; ?></td>
        <td><?= l("Edit", Path::admin_program_edit($program->id)); ?></td>
        <td><?= l("Delete", Path::admin_program_delete($program->id), array("method" => "delete")); ?></td>
    </tr>
    <tr style="border-bottom:1px solid #002e5c;">
        <td colspan='6'>
            <div style="margin:0 12px;padding:4px;font-size:8pt;">
            Privileged Users:<br/><br />
                <table style="width:400px;">
                    <th style="width:33%">Privilege</th><th style="width:33%">User</th><th style="width:33%">&nbsp;</th>
            <? foreach ($users as $user): ?>
                    <tr>
                        <td><?= Ability::$ability_level_strings[$user['level']] ?></td>
                        <td><?= "{$user['first_name']} {$user['last_name']}"; ?></td>
                        <td><?= l('remove privilege', Path::admin_ability_remove('Program', $program->id, "uid={$user['id']}")); ?></td>
                    </tr>
            <? endforeach; ?>
                </table>
                <p>
                <?= l('add privileged user', Path::admin_ability_add('Program', $program->id)); ?>
                </p>
            </div>
        </td>
    </tr>
<? endforeach; ?>
</table>
