<p><strong>Programs</strong></p>
<?= l("Add New Program", path::admin_program_add());?>
<table>
    <tr>
        <th>Program</th>
        <th>Weight</th>
        <th>Description</th>
        <th>Type</th>
        <th>Can Have Team Pages</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
<? foreach ($this->programs as $program): ?>
    <tr>
        <td><?= $program->name; ?></td>
        <td><?= $program->weight; ?></td>
        <td><?= $program->description; ?></td>
        <td><?= $program->Type(); ?></td>
        <td><?= $program->has_teams ? 'yes': 'no'; ?></td>
        <td><?= l("Edit", Path::admin_program_edit($program->id)); ?></td>
        <td><?= l("Delete", Path::admin_program_delete($program->id), array("method" => "delete")); ?></td>
    </tr>
<? endforeach; ?>
</table>
