<h1 class="title">Change Password</h1>
<?= l("back", GetReturnURL()); ?>
<br />
<br />
<?= GetErrorsFor($this->user); ?>
<?= FormTag("change_password", \simp\Request::PUT); ?>
<table class="form">
    <tr>
        <th class="label">New Password</th>
        <td class="entry"><?= PasswordField($this->user, "password"); ?></td>
    </tr>
    <tr>
        <th class="label">Confirm Password</th>
        <td class="entry"><?= PasswordField($this->user, "password_verification"); ?></td>
    </tr>
</table>
<input type="submit" value="Change Password" />
<?= EndForm(); ?>
    
