<h2><?= $this->user->first_name; ?>'s Preferences</h2>
<?= l("change password", Path::user("change_pass")); ?> |
<?= l("back", GetReturnURL()); ?>
<br />
<br />
<?= GetErrorsFor($this->user); ?>
<?= FormTag("edit", \simp\Request::PUT, Path::user_edit($this->user->id)); ?>
<table class="form">
    <tr>
        <th>My User Id</th>
        <td><?= $this->user->login; ?></td>
    </tr>
    <tr>
        <th>My First Name</th>
        <td><?= TextField($this->user, "first_name"); ?></td>
    </tr>
    <tr>
        <th>My Last Name</th>
        <td><?= TextField($this->user, "last_name"); ?></td>
    </tr>
    <tr>
        <th>My Email Address</th>
        <td><?= TextField($this->user, "email"); ?></td>
    </tr>
    <tr>
        <th>Send Emails to Me</th>
        <td>
            <?= RadioButton($this->user, "email_html", 0); ?> in plain text <br />
            <?= RadioButton($this->user, "email_html", 1); ?> in HTML 
        </td>
    </tr>
    <tr>
        <th>Send Site Notifications to Me</th>
        <td>
            <?= RadioButton($this->user, "notification_type", User::EMAIL); ?> via Email<br />
            <?= RadioButton($this->user, "notification_type", User::MESSAGE); ?> via Site Message<br />
            <?= RadioButton($this->user, "notification_type", User::EMAIL_AND_MESSAGE); ?> via Email and Site Message<br />
            <?= RadioButton($this->user, "notification_type", User::NONE); ?> don't send any notifications
        </td>
    </tr>
<? /*
    <tr>
        <th>Change Password</th>
        <td><?= PasswordField($this->user, "password"); ?></td>
    </tr>
    <tr>
        <th>Verify Password</th>
        <td><?= PasswordField($this->user, "password_verification"); ?></td>
    </tr>
 */
?>
    <tr>
        <th>My Timezone:</th><td><?=SimpleSelect($this->user, 'timezone', SupportedTimeZones());?>
    </tr>
</table>
<input type="submit" value="Update Profile"\>
<?= EndForm(); ?>
    
        
