<h1 class='title'>Coaches</h1>
<?= l("Add Coach", Path::admin_coaches_add()); ?>
<? if (count($this->coaches) < 1): ?>
    <p>No coaches have been added.  <?= l("Add a new coach", Path::admin_coaches_add()); ?>
<? else: ?>
    <table class="pretty">
        <tr>
            <th>Name</th><th>Title</th><th>Status</th><th colspan="3">&nbsp;</th>
        </tr>
    <? foreach($this->coaches as $coach): ?>
        <tr>
            <td><?= $coach->first_name; ?> <?= $coach->last_name; ?></td>
            <td><?= Coach::$coach_titles[$coach->title]; ?></td>
        <? if ($coach->active == true): ?>
            <td>ACTIVE</td>
            <td><?= l("deactivate", Path::admin_coaches_deactivate($coach->id)); ?></td>
        <? else: ?>
            <td>inactive</td>
            <td><?= l("activate", Path::admin_coaches_activate($coach->id)); ?></td>
        <? endif; ?>
            <td><?= l("edit", Path::admin_coaches_edit($coach->id)); ?></td>
            <td><?= l("remove", Path::admin_coaches_delete($coach->id), array("method" => "delete")); ?></td>
        </tr>
    <? endforeach; ?>
<? endif; ?>
