<?
$opts = array();
for ($i = 1; $i < 31; $i++)
{
    $opts[$i] = $i;
}
?>
<table>
    <tr>
        <td style="text-align:right;">Repeat every:</td>
        <td><?= SimpleSelect($this->event, 'repeat_interval', $opts); ?> years(s)</td>
    </tr>
    <tr>
        <td style="text-align: right">Ending: </td>
        <td>
            <?= RadioButton($this->event, "repeat_end", "occurrences"); ?> after
            <?= TextField($this->event, "occurrences", array('size' => 4)); ?> occurrences
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <?= RadioButton($this->event, "repeat_end", "last_repeat_date"); ?> on
            <?= TextField($this->event, "last_repeat_date", array('size' => 10)); ?>
        </td>
    </tr>
</table>
