<table>
    <tr>
<? 
$opts = array();
for ($i = 1; $i < 31; $i++)
{
    $opts[$i] = $i;
}
?>
        <td style="text-align: right">Repeat every:</td> 
        <td><?= SimpleSelect($this->event, 'repeat_interval'); ?> day(s)</td>
    </tr>
    <tr>
        <td style="text-align: right">Staring on:</td> 
        <td><?= FormatDateTime($this->event->start_date, "m/d/Y"); ?></td>
    </tr>
        
<table>
