<fieldset>
    <legend>What</legend>
    <table class="form">
        <tr>
            <td><strong>Select category to which event belongs:</strong></td>
            <td><?= SimpleSelect($this->event, 'entity_id', $this->programs); ?></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td><strong>Enter a short title:</strong></td>
            <td><?= TextField($this->event, 'short_title', array('size' => 32)); ?></td>
            <td>Max characters: 32</td>
        </tr>
        <tr>
            <td><strong>Enter title:</strong></td>
            <td colspan="2"><?= TextField($this->event, 'title', array('size' => 80));?></td>
        </tr>
        <tr>
            <td><strong>Description:</strong></td>
            <td colspan="2"><?= TextArea($this->event, 'description', 4, 70); ?></td>
        </tr>
        <tr>
            <td><strong>Location:</strong></td>
            <td colspan="2"><?= TextField($this->event, 'location', array('size' => 80));?></td>
        </tr>
    </table>
</fieldset>
<fieldset>
    <legend>When</legend>
        All Day? <?= CheckBoxButton($this->event, "all_day"); ?><br />
        from
        <?= TextField($this->event, 'start_date', array("id" => "start_date")); ?>
        <? if ($this->event->all_day == false): ?>
        at
        <?= TextField($this->event, 'start_time', array("id" => "start_date")); ?>
        <? endif; ?>
        - to -
        <?= TextField($this->event, 'end_date', array("id" => "start_date")); ?>
        <? if ($this->event->all_day == false): ?>
        at
        <?= TextField($this->event, 'end_time', array("id" => "start_date")); ?>
        <? endif; ?>
        <br />
        <br />
        This event repeats: &nbsp;
        daily <?= CheckBoxButton($this->event, 'repeat_daily'); ?>&nbsp;&nbsp;
        weekly <?= CheckBoxButton($this->event, 'repeat_weekly'); ?>&nbsp;&nbsp;
        monthly <?= CheckBoxButton($this->event, 'repeat_monthly'); ?>&nbsp;&nbsp;
        annually <?= CheckBoxButton($this->event, 'repeat_annually'); ?>
    <fieldset>
        <legend>Event Repetition Information</legend>
        <? 
        if ($this->event->repeat_daily) include "_daily.phtml";
        else if ($this->event->repeat_weekly) include "_weekly.phtml";
        else if ($this->event->repeat_monthly) include "_monthly.phtml";
        else if ($this->event->repeat_annually) include "_annually.phtml";
        ?>
    </fieldset>
</fieldset>
