<?
$opts = array();
for ($i = 1; $i < 31; $i++)
{
    $opts[$i] = $i;
}
?>
<table>
    <tr>
        <td style="text-align:right;">Repeat every:</td>
        <td><?= SimpleSelect($this->event_info, 'repeat_interval', $opts); ?> months(s)</td>
    </tr>
    <tr>
        <td style="text-align:right;">Repeat by:</td>
        <td><?= RadioButton($this->event_info, "repeat_by", "dom"); ?> day of the month</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><?= RadioButton($this->event_info, "repeat_by", "dow"); ?> day of the week</td>
    </tr>
    <tr>
        <td style="text-align: right">Ending: </td>
        <td>
            <?= RadioButton($this->event_info, "repeat_end", "occurrences"); ?> after
            <?= TextField($this->event_info, "recur_count", array('size' => 4)); ?> occurrences
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <?= RadioButton($this->event_info, "repeat_end", "last_repeat_date"); ?> on
            <?= TextField($this->event_info, "end_date_str", array('size' => 10)); ?>
        </td>
    </tr>
</table>
    
