<? 
$opts = array();
for ($i = 1; $i < 31; $i++)
{
    $opts[$i] = $i;
}
$days = array("Su", "M", "Tu", "W", "Th", "F", "Sa");
?>
<table>
    <tr>
        <td style="text-align: right">Repeat every:</td>
        <td><?= SimpleSelect($this->event_info, 'repeat_interval', $opts); ?> week(s)</td>
    </tr>
    <tr>
        <td style="text-align: right">Repeat On:</td>
        <td>
            <? $mask = $this->event_info->day_mask; ?>
            <? foreach($days as $i=>$day): ?>
                <?= $day; ?>
                <? $checked = $mask[$i] == 1 ? "checked=\"true\" " : " "; ?>
            <input type='hidden' name='EventInfo[day_mask][<?=$i;?>]' value='0' />
            <input type='checkbox' name='EventInfo[day_mask][<?=$i;?>]' value='1' <?= $checked ?>/>
            &nbsp;
            <? endforeach; ?>
        </td>
    </tr>
    <tr>
        <td style="text-align: right">Ending: </td>
        <td>
            <?= RadioButton($this->event_info, "repeat_end", "occurrences"); ?> after
            <?= TextField($this->event_info, "recur_count", array('size' => 4)); ?> occurrences
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <?= RadioButton($this->event_info, "repeat_end", "last_repeat_date"); ?> on
            <?= TextField($this->event_info, "end_date_str", array('size' => 10)); ?>
        </td>
    </tr>
</table>
