<h1>Events</h1>
<div style="text-align:center;">
<? 
$prev_year = $next_year = $this->year;
$prev_month = $this->month - 1;
$next_month = $this->month + 1;
switch ($this->month)
{
case 1:
    $prev_month = 12;
    $prev_year--;
    break;
case 12:
    $next_month = 1;
    $next_year++;
}
?>
<?= l("&lt;prev", Path::content_event_calendar($prev_year, $prev_month)); ?>
<strong> <?= $this->month; ?>/<?= $this->year; ?> </strong>
<?= l("next&gt;", Path::content_event_calendar($next_year, $next_month)); ?>
<table style="width:100%;">
    <tr>
        <td>Sun</td> <td>Mon</td> <td>Tue</td> <td>Wed</td> <td>Thu</td> <td>Fri</td> <td>Sat</td>
    </tr>
    <tr>
<? $d = 0; ?>
<? $numdays = count($this->dates); ?>
<? foreach ($this->dates as $date): ?>
<?      if ($d % 7 == 0): ?>
    </tr>
<?          if ($d < $numdays): ?>
    <tr>
<?          endif; ?>
<?      endif; ?>
        <td class="<?= $date['class']; ?>">
            <?= $date['d']; ?>
            <?= l("add event", Path::content_event_add($date['y'], $date['m'], $date['d'])); ?><br />
            <? foreach ($date['events'] as $event): ?>
            <?= $event->title; ?> <br />
            <? endforeach; ?>
        </td>
<?      $d++; ?>
<? endforeach; ?>
</table>
</div>
