<h1 class="title">Team Accounts Managed by you</h1>
<? foreach ($this->team_account_info as $info): ?>
<h2><?= $info['team_name']; ?></h2>
    <? if (count($info['accounts']) > 0): ?>
<table class="pretty">
    <tr><th>Player<br />(select user to manage)</th><th>Starting Balance</th><th>Current Balance</th><th colspan="3">Actions</th></tr>
        <? foreach ($info['accounts'] as $account): ?>
    <tr>
        <td><?= l("{$account->last_name}, {$account->first_name}", Path::admin_account_show($account->id)); ?></td>
        <td><?= $account->starting_balance; ?></td>
        <td><?= $account->current_balance; ?></td>
        <td>
            <?= l("add transaction", Path::admin_transaction_add($account->id)); ?>
        </td>
        <td>
            <?= l("edit account", Path::admin_account_edit($account->id)); ?>
        </td>
        <td>
            <?= l("delete account", Path::admin_account_delete($account->id), array('method' => 'delete')); ?>
        </td>
    </tr>
        <? endforeach; ?>
</table>
<p> <?= l("Create Account", Path::admin_account_add($info['team_id'])); ?></p>
    <? else: ?>
<p>No accounts for that team.  <?= l("create one", Path::admin_account_add($info['team_id'])); ?></p>
    <? endif; ?>
<? endforeach; ?>
