<? 
$user_opts = array();
foreach ($this->users as $u)
{
    $user_opts[$u['id']] = "{$u['first_name']} {$u['last_name']}";
}
?>
<h1 class="title">Account for <?= "{$this->account->first_name} {$this->account->last_name}" ?></h1>
<?= l("Back to account list", Path::admin_account()); ?>
<fieldset><legend>Website User Accounts with access</legend>
<? if (count($this->account->users) > 0): ?>
<table class="pretty">
    <tr><th>Name</th><th>Login ID</th><th>Email Address</th><th>Action</th></tr>
    <? foreach ($this->account->users as $u): ?>
        <? unset($user_opts[$u->id]); ?>
    <tr>
        <td><?= "{$u->first_name} {$u->last_name}"; ?></td>
        <td><?= $u->login; ?></td>
        <td><?= ObsEmailLink($u->email); ?></td>
        <td><?= l("Remove from account", Path::admin_account_deluser($this->account->id, "u=$u->id")); ?></td>
    </tr>
    <? endforeach; ?>
</table>
<? else: ?>
    <p>No website users associated with this account.</p>
<? endif; ?>
<? if (count($user_opts) > 0): ?>
<?= FormTag('account_user', \simp\Request::POST, Path::admin_account_adduser($this->account->id)); ?>
    <?= SimpleSelect($this->account, 'new_user', $user_opts); ?>
    <input type="submit" value="Add User" />
<?= EndForm(); ?>
<? endif; ?>
</fieldset>
<fieldset><legend>Account Register</legend>
<div class="account-wrap">
    <table class="account top">
        <tr class="balance">
            <td class="date">&nbsp;</td>
            <td class="desc">Starting Balance</td>
            <td class="amount">&nbsp;</td>
            <td class="amount">&nbsp;</td>
    <? $class = $this->account->start_balance < 0 ? "debit" : "credit"; ?>
            <td class="amount <?= $class; ?>"><?= $this->account->starting_balance; ?></td>
        </tr>
        <tr><th>Date</th><th>Description</th><th>Credit</th><th>Debit</th><th>Balance</th></tr>
    </table>
    <div class="account">
        <? $balance = $this->account->start_balance; ?>
        <? $odd = true; ?>
        <table class="account">
        <? foreach ($this->transactions as $txn): ?>
            <tr class="<?=($odd=!$odd)?'odd':'even';?>">
                <td class="date"><?= $txn->date; ?></td>
                <td class="desc">
                    <?= $txn->description; ?> 
                    <?= l("[edit]", Path::admin_transaction_edit($txn->id)); ?>
                    <?= l("[delete]", Path::admin_transaction_delete($txn->id), array('method' => 'delete')); ?>
                </td>
                <td class="amount credit"><? $txn->type == Txn::CREDIT ? print($txn->amount) : false; ?></td>
                <td class="amount debit"><? $txn->type == Txn::DEBIT ? print($txn->amount) : false; ?></td>
            <? $balance = $balance + $txn->value; ?>
            <? $class = $balance < 0 ? "debit" : "credit"; ?>
                <td class="amount <?= $class; ?>"><?= ToDollars($balance); ?></td>
            </tr>
        <? endforeach; ?>
        </table>
    </div>
    <table class="account bottom">
        <tr class="balance">
            <td class="date"><?= FormatDateTime(time(), "m/d/Y"); ?></td>
            <td class="desc">Current Balance</td>
            <td class="amount">&nbsp;</td>
            <td class="amount">&nbsp;</td>
        <? $class = $balance < 0 ? "debit" : "credit"; ?>
            <td class="amount <?= $class; ?>"><?= ToDollars($balance); ?></td>
        </tr>
    </table>
</div>
    <p><?= l("Add transaction", Path::admin_transaction_add($this->account->id)); ?></p>
</fieldset>


