<? 
$user_opts = array();
foreach ($this->users as $u)
{
    $user_opts[$u['id']] = "{$u['first_name']} {$u['last_name']}";
}
?>
<?= IncludeCSS("account"); ?>
<h1 class="title">Account for <?= "{$this->account->first_name} {$this->account->last_name}" ?></h1>
<?= l("Back to account list", Path::admin_account()); ?>
<fieldset><legend>Website User Accounts with access</legend>
<? if (count($this->account->users) > 0): ?>
<table class="pretty">
    <tr><th>Name</th><th>Login ID</th><th>Email Address</th><th>Action</th></tr>
    <? foreach ($this->account->users as $u): ?>
        <? unset($user_opts[$u->id]); ?>
    <tr>
        <td><?= "{$u->first_name} {$u->last_name}"; ?></td>
        <td><?= $u->login; ?></td>
        <td><?= ObsEmailLink($u->email); ?></td>
        <td><?= l("Remove from account", Path::admin_account_deluser($this->account->id, "u=$u->id")); ?></td>
    </tr>
    <? endforeach; ?>
</table>
<? else: ?>
    <p>No website users associated with this account.</p>
<? endif; ?>
<? if (count($user_opts) > 0): ?>
<?= FormTag('account_user', \simp\Request::POST, Path::admin_account_adduser($this->account->id)); ?>
    <?= SimpleSelect($this->account, 'new_user', $user_opts); ?>
    <input type="submit" value="Add User" />
<?= EndForm(); ?>
<? endif; ?>
</fieldset>
<fieldset><legend>Account Register</legend>
    <table class="account">
        <tr><th>Date</th><th>Description</th><th>Credit</th><th>Debit</th><th>Balance</th></tr>
        <tr class="balance">
            <td>&nbsp;</td>
            <td>Starting Balance</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
    <? $class = $this->account->start_balance < 0 ? "debit" : "credit"; ?>
            <td class="<?= $class; ?>"><?= $this->account->starting_balance; ?></td>
        </tr>
    <? $balance = $this->account->start_balance; ?>
    <? foreach ($this->transactions as $txn): ?>
        <tr>
            <td><?= $txn->date; ?></td>
            <td><?= $txn->description; ?> <?= l("[edit]", Path::admin_transaction_edit($txn->id)); ?></td>
            <td class="credit"><? $txn->type == Txn::CREDIT ? print($txn->amount) : false; ?></td>
            <td class="debit"><? $txn->type == Txn::DEBIT ? print($txn->amount) : false; ?></td>
        <? $balance = $balance + $txn->value; ?>
        <? $class = $balance < 0 ? "debit" : "credit"; ?>
            <td class="<?= $class; ?>"><?= ToDollars($balance); ?></td>
        </tr>
    <? endforeach; ?>
    </table>
    <p><?= l("Add transaction", Path::admin_transaction_add($this->account->id)); ?></p>
</fieldset>


