<?
$ys = \Team::GetCurrentYearStart();
$ye = \Team::GetCurrentYearEnd();
?>
<fieldset>
    <legend>Team Information</legend>
    <table class="form">
        <? if ($this->GetUser()->CanPublish('Program', $this->team->program_id)): ?>
        <tr>
            <th class='label'>Select the program to which team page belongs:</th>
            <td class='entry'><?= SimpleSelect($this->team, 'program_designator', $this->programs); ?></td>
        </tr>
        <? endif; ?>
        <tr>
            <th class='label'>Enter name of team:</th>
            <td class='entry'><?= TextField($this->team, 'short_name', array('size' => 32)); ?></td>
        </tr>
        <tr>
            <th class='label'>Select the division this team *CURRENTLY belongs to:</strong><br \>
                *
                <em>between
                    <?= FormatDateTime($ys, "F jS, Y"); ?>
                    and 
                    <?= FormatDateTime($ye, "F jS, Y"); ?>
                </em>
            </td>
            <td class='entry'><?= SimpleSelect($this->team, 'year', $this->team->GetDivisions()); ?></td>
        </tr>
        <tr>
            <th class='label'>Select team gender:</th>
            <td class='entry'><?= SimpleSelect($this->team, 'gender', $this->team->GetGenders()); ?></td>
        </tr>
        <? if ($this->GetParam('format') != 'no_template'): ?>
        <tr>
            <th class='label'>Team Photo:</th>
            <td class='entry'><?= FileSelect($this->team, 'image'); ?></td>
        </tr>
        <? endif; ?>
        <tr>
            <th class='label'>GotSoccer Page:</th>
            <td class='entry'><?= TextField($this->team, 'gotsoccer', array('size' => 40)); ?></td>
        </tr>
    </table>
</fieldset>
