<h1 class="title"><?= $this->team->name; ?> Administration</h1>
<div class="cfg-group">
    <h1>Team Info</h1>
    <table>
        <tr>
            <th><?= l("Edit Team Information", Path::admin_teams_edit($this->team->id)); ?></th>
            <th><?= l("Manage Members", Path::admin_user("team_manager", $this->team->id)); ?></th>
            <th><?= l("Manage Articles", Path::content_news()); ?></th>
            <th><?= l("Manage Images", Path::content_image()); ?></th>
            <th><?= l("Manage Events", Path::content_event()); ?></th>
            <th><?= l("Manage 'Pages'", Path::content_page()); ?></th>
        </tr>
        <tr>
            <td>Edit this team's information (team photo, name, etc.)</td>
            <td>Add/Modify/Remove which users have access to this team</td>
            <td>Create/Edit/Remove news articles for this team</td>
            <td>Upload/Remove images for this team</td>
            <td>Create/Edit/Remove calendar events for this team</td>
            <td>Create/Edit/Remove special pages for this team</td>
        </tr>
    </table>
</div>
