<h1 class="title">Field Availability</h1>
<?= GetErrorsFor($this->elements); ?>
<?= FormTag("fields", \simp\Request::POST); ?>
<fieldset><legend>Enter Date/Time To Check Availability</legend>
<table class="form">
    <tr>
        <th class="label">Division</th>
        <td class="entry"><?= SimpleSelect($this->elements, "format", Field::$formats); ?></th>
    </tr>
    <tr>
        <th class="label">Date</th>
<? $args = "maxDate: '+4m', minDate: '+0d', changeYear: false, changeMonth: true, showOn: 'both', showAnim: 'drop', showButtonPanel: 'true', yearRange: 'c-18:c+18'"; ?>
        <td class="entry"><?= DatePicker($this->elements, "date", array('args' => $args)); ?></th>
    </tr>
</table>
</fieldset>
<input type="submit" value="Check..." />
<?= EndForm(); ?>
