<?
$times = GenerateTimeSlots("7:00", "21:00", 30);
$header = "<tr><th style='width:50px;'>Field</th>";
foreach ($times as $t)
{
    $header .= "<th class='vert'><span>" . strftime("%l:%M%p", $t) . "</span></th>";
}
$header .= "</tr>\n";
$fields = $this->fields;
?>
<h1 class="title">
Field Availability
</h1> 
<h2><?= Field::$formats[$this->format]; ?> Fields</h2>
<h3><?= FormatDateTime($this->date, "l, F j, Y"); ?></h3>
<table class="pretty field-u">
    <?= $header; ?>
<? foreach ($fields as $field): ?>
    <tr>
        <th class="small"><?= $field->name; ?></th>
    <? foreach ($field->GetAvailability($this->date, $times) as $slot): ?>
        <td class="<?= $slot; ?>">&nbsp;</td>
    <? endforeach; ?>
    </tr>
<? endforeach; ?>
</table>
<table class="pretty field-legend">
<tr><th colspan="2">Legend</th></tr>
<tr><td class="closed">Closed</td><td>Complex is closed at this time</td></tr>
<tr><td class="open">Available</td><td>Fields have no game scheduled at this time</td></tr>
<tr><td class="game">Unavailable</td><td>A game is currently scheduled at this time</td></tr>
<tr><td class="black">Blackout</td><td>There is an event to be scheduled at the fields at this time, thus they are unavailable</td></tr>
</table>
