<h1 class="title">Content Console</h1>
<div class="cfg-group">
    <h1>Content Management</h1>
    <table>
        <tr>
            <th><?= l("Articles", Path::content_news()); ?></th>
            <th><?= l("Events", Path::content_event()); ?></th>
            <th><?= l("Tournaments", Path::content_tournament()); ?></th>
            <th><?= l("Camps", Path::content_camp()); ?></th>
            <th><?= l("Images", Path::content_image()); ?></th>
        </tr>
        <tr>
            <td>Manage articles for various programs (create, edit, delete)</td>
            <td>Manage events (calendar) for various programs (create, edit, delete)</td>
            <td>Manage tournament information (create, edit, delete)</td>
            <td>Manage camp information (create, edit, delete)</td>
            <td>Manage images to be used with articles (upload, bulk upload, delete)</td>
        </tr>
    </table>
</div>
