<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
        <title>
            <?= SiteName(); ?>
        </title>
        <?= IncludeCSS("style.css"); ?>
    </head>
    <body>
        <div id="header">
            <div id="user-menu">
                <ul class = "menu">
            <? if ($this->UserLoggedIn()):?>
                    <li>Logged in as: <?= $this->GetUser()->login?></li>
                    <li><?= l("logout", Path::user_logout()); ?> </li>
                    <li><?= l("my profile", Path::user_edit()); ?> </li>
                <? if ($this->GetUser()->super): ?>
                    <li><?= l("administration", Path::administrator()); ?> </li>
                    <li><?= l("manage content", Path::content()); ?></li>
                <? endif; ?>
            <? else: ?>
                    <li><?= l("login", Path::user_login()); ?></li>
                    <li><?= l("create account", Path::user_signup()); ?></li>
            <? endif; ?>
                </ul>
            </div>
            <div id="main-menu">
                <!--
                <div id="min"</div></div>
                <ul class="menu">
                </ul>
                -->
                <? \simp\Module::Show("MainMenu"); ?>
            </div>
            <!--div id="notice">
            </div-->
            <? \simp\Module::Show("Notice"); ?>
        </div>
        <div class="colmask">
            <div class="middle">
                <div class="left">
                    <div class="col1">
                        <?=GetFlash();?>
        <!-- div class="breadcrumb"><?//= MainMenu::GetBreadcrumb(); ?></div-->
                        <?= $this->content; ?>
                        <!--div style="height:400px;"></div-->
                    </div>
                    <div class="col2">
                        <? if (!isset($this->event_data)) $this->event_data = array('entity_type' => 'Program'); ?>
                        <? \simp\Module::Show("Events", $this->event_data); ?>
                    </div>
                    <div class="col3">
                        <? \simp\Module::Show("FieldConditions"); ?>
                        <? 
                        $history = GetHistory();
                        foreach ($history as $url): ?>
                            <?= l($url, $url); ?>
                        <? endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer">
            &copy; 2011 South Lakes Soccer Club
        </div>
    </body>
</html>
