<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
        <title>
            <?= SiteName(); ?>
        </title>
        <link rel="shortcut icon" href="favicon.ico" />
        <?= IncludeCSS("style.css"); ?>
        <?= IncludeJS("jquery.js"); ?>
    </head>
    <body>
    <div id="wrapper">
        <? \simp\Module::Show("Notices"); ?>
        <div id="header">
            <div id="user-menu">
                <ul class = "menu">
            <? if ($this->UserLoggedIn()):?>
                <? $user = $this->GetUser();
                   $unread_count = $user->unread_message_count;
                   $link_img = $unread_count > 0 ?
                       "<img src=\"" . GetImagePath("email_open_image.png") . "\" style=\"vertical-align:bottom\" />" :
                       "<img src=\"" . GetImagePath("email.png") . "\" style=\"vertical-align:bottom\" />";
                ?>
                    <li>Logged in as: <?= $user->login?></li>
                    <li><?= l($link_img, Path::message()); ?></li>
                    <li><?= l("logout", Path::user_logout()); ?> </li>
                    <li><?= l("preferences", Path::user_edit()); ?> </li>
                <? if ($this->GetUser()->super): ?>
                    <li><?= l("administration", Path::administrator()); ?> </li>
                    <li><?= l("manage content", Path::content()); ?></li>
                <? endif; ?>
            <? else: ?>
                    <li><?= l("login", Path::user_login()); ?></li>
                    <li><?= l("create account", Path::user_signup()); ?></li>
            <? endif; ?>
                </ul>
            </div>
            <div id="main-menu">
                <!--
                <div id="min"</div></div>
                <ul class="menu">
                </ul>
                -->
                <? \simp\Module::Show("MainMenu", array('current' => $this->cur_page)); ?>
            </div>
        </div>
        <?=GetFlash();?>
        <div class="colmask">
            <div class="middle">
                <div class="left">
                    <div class="col1">
        <!-- div class="breadcrumb"><?//= MainMenu::GetBreadcrumb(); ?></div-->
                        <div class="section">
                            <?= $this->content; ?>
                        </div>
                        <!--div style="height:400px;"></div-->
                    </div>
                    <div class="col2">
                        <? \simp\Module::Show("Events"); //, array('entity_type' => GetEntityType(), 'entity_id' => GetEntityId())); ?>
                        <? \simp\Module::Show("RecentUpdates"); ?>
                    </div>
                    <div class="col3">
                        <? \simp\Module::Show("FieldConditions"); ?>
                        <? \simp\Module::Show("Links"); ?>
                        <? \simp\Module::Show("Information"); ?>
                        <? /* Don't know what the hell this is 
                        $history = GetHistory();
                        foreach ($history as $url): ?>
                            <?= l($url, $url); ?>
                        <? endforeach; ?>
                         */ ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="push">
        </div>
    </div>
    <div id="footer">
        &copy; 2011 South Lakes Soccer Club
    </div>
    </body>
</html>
