<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
        <title>
            <?= SiteName(); ?>
        </title>
        <?= IncludeCSS("ce_layout.css"); ?>
        <?= IncludeCSS("style.css"); ?>
        <?= IncludeCSS("content.css"); ?>
        <?= IncludeCSS("custom-theme/jquery-ui.css"); ?>
        <?= IncludeJS("jquery.js"); ?>
        <?= IncludeJS("jquery-ui.js"); ?>
        <?= IncludeJS("tiny_mce/jquery.tinymce.js"); ?>
        <?= IncludeJS("editor.js"); ?>
        <script type="text/javascript">
$(function($) {
    $(document).ready(function() {
        loadEditor($("textarea.wysiwyg"), "<?= GetJSPath("tiny_mce/tiny_mce.js"); ?>" );
        $(".date-picker").datepicker();
    });
});
        </script>
        <meta name='url_base' content='<?=Path::home()?>' />
    </head>
    <body>
        <div id="header">
            <div id="user-menu">
                <ul class = "menu">
                <? $user = $this->GetUser();
                   $unread_count = $user->unread_message_count;
                   $link_img = $unread_count > 0 ?
                       "<img src=\"" . GetImagePath("email_open_image.png") . "\" style=\"vertical-align:bottom\" />" :
                       "<img src=\"" . GetImagePath("email.png") . "\" style=\"vertical-align:bottom\" />";
                ?>
                    <li>Logged in as: <?= $user->login?></li>
                    <li><?= l($link_img, Path::message()); ?></li>
                    <li><?= l("logout", Path::user_logout()); ?> </li>
                    <li><?= l("my profile", Path::user_edit()); ?> </li>
                <? if ($this->GetUser()->super): ?>
                    <li><?= l("administration", Path::administrator()); ?> </li>
                <? endif; ?>
                </ul>
            </div>
            <div id="main-menu">
                <? \simp\Module::Show("MainMenu"); ?>
            </div>
        </div>
        <div id="content-menu">
            <ul class="menu">
                <li><?= l("Articles", Path::content_news()); ?></li>
                <li><?= l("Events", Path::content_event()); ?></li>
                <li><?= l("Tournaments", Path::content_tournament()); ?></li>
                <li><?= l("Camps", Path::content_camp()); ?></li>
                <li><?= l("Images", Path::content_image()); ?></li>
                <li>Documents</li>
            </ul>
        </div>
        <?=GetFlash();?>
        <div id="content">
            <?= $this->content ?>
        </div>
    </body>
</html>
        
